# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Artifacts < Formula
  desc "Inigo CLI"
  homepage "https://www.inigo.io"
  version "0.17.0"

  on_macos do
    url "https://github.com/inigolabs/artifacts/releases/download/v0.17.0/cli_macos_all.tar.gz"
    sha256 "27af6d9048a68bdb793361ef35edbbb9e296949905a61ba02a53ce1c09a7f7ff"

    def install
      bin.install "inigo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inigolabs/artifacts/releases/download/v0.17.0/cli_linux_arm64.tar.gz"
      sha256 "b0595f9667ef5ec7144d32dc491f43d635ebc5d680f19a0d070157d9c6c64d79"

      def install
        bin.install "inigo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/inigolabs/artifacts/releases/download/v0.17.0/cli_linux_x86_64.tar.gz"
      sha256 "697ce673b76435652498294b5f59055b27482a2818de27ed5350f7b903baf164"

      def install
        bin.install "inigo"
      end
    end
  end
end
