# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InigoGateway < Formula
  desc "Inigo Gateway"
  homepage "https://www.inigo.io"
  version "0.30.17"

  on_macos do
    url "https://github.com/inigolabs/artifacts/releases/download/v0.30.17/gateway_darwin_all.tar.gz"
    sha256 "72f695a20435f52c318dd05ac033dd827b2919bb5f7abdd245ff592e08ce0947"

    def install
      bin.install "inigo_gateway"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inigolabs/artifacts/releases/download/v0.30.17/gateway_linux_arm64.tar.gz"
      sha256 "d2eb487f9d11fc452ffb4d5db29c52dd7b47b151778d03340d6acde6907285c4"

      def install
        bin.install "inigo_gateway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/inigolabs/artifacts/releases/download/v0.30.17/gateway_linux_amd64.tar.gz"
      sha256 "51bb361e66652833b9e4cab86a9cd303a237c05614112b0b6e0729a533b741f2"

      def install
        bin.install "inigo_gateway"
      end
    end
  end
end
