# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InigoGateway < Formula
  desc "Inigo Gateway"
  homepage "https://www.inigo.io"
  version "1.0.0"

  on_macos do
    url "https://github.com/inigolabs/artifacts/releases/download/1.0.0/gateway_darwin_all.tar.gz"
    sha256 "92aa20b73c72f44d1001184c898876a975d9fa379a0237039934c136e27e2117"

    def install
      bin.install "inigo_gateway"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/inigolabs/artifacts/releases/download/1.0.0/gateway_linux_amd64.tar.gz"
      sha256 "399379ae5863b6de85fbb12912bc439ee513f390a61cd83e1b2d2dbb091235bd"

      def install
        bin.install "inigo_gateway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inigolabs/artifacts/releases/download/1.0.0/gateway_linux_arm64.tar.gz"
      sha256 "03dd60b4140bbe9b28d937fce3ba147395e5cafead613887b6b214be49ba637f"

      def install
        bin.install "inigo_gateway"
      end
    end
  end
end
