# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revgen < Formula
  desc "Only run go:generate when code changes"
  homepage "https://github.com/inigolabs/revgen"
  version "0.0.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/inigolabs/revgen/releases/download/v0.0.14/revgen_macos_arm64.tar.gz"
      sha256 "acdcebba81e124a65a36b35138018f377c51f7152c5fd82a37da6055efe30483"

      def install
        bin.install "revgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/inigolabs/revgen/releases/download/v0.0.14/revgen_macos_x86_64.tar.gz"
      sha256 "e65d044bf499a42b27ca1fd975488899be63b5d61411e66292c67d6cb418a1bb"

      def install
        bin.install "revgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inigolabs/revgen/releases/download/v0.0.14/revgen_linux_arm64.tar.gz"
      sha256 "a3519e47934c69c985d6e20af393f00a8e8617ce19b75caa762cae36daba7c02"

      def install
        bin.install "revgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/inigolabs/revgen/releases/download/v0.0.14/revgen_linux_x86_64.tar.gz"
      sha256 "110c24a84579ce75136fa08e2b86ced9a1f7143a1af108470e2189aae8d61507"

      def install
        bin.install "revgen"
      end
    end
  end
end
