# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revgen < Formula
  desc "Only run go:generate when code changes"
  homepage "https://github.com/inigolabs/revgen"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inigolabs/revgen/releases/download/v0.0.10/revgen_macos_x86_64.tar.gz"
      sha256 "6aabf6f98ed90b3cf38c8f94e1bf46f7bd4203e6714a946221f1586b122f8496"

      def install
        bin.install "revgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inigolabs/revgen/releases/download/v0.0.10/revgen_macos_arm64.tar.gz"
      sha256 "0e49770758c3467edc412a3ad4fc87dd7220c4b2a82c4ab861b117a1e05f2e0f"

      def install
        bin.install "revgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inigolabs/revgen/releases/download/v0.0.10/revgen_linux_arm64.tar.gz"
      sha256 "3b0e6fea8b5a38128200b6b0ee6c3f1fa9520f6a969d976477b641cfd69f7ecc"

      def install
        bin.install "revgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/inigolabs/revgen/releases/download/v0.0.10/revgen_linux_x86_64.tar.gz"
      sha256 "f909133c89a961237c926e6647cf423abc61df0588601048d4d8e6efefb8fca5"

      def install
        bin.install "revgen"
      end
    end
  end
end
